function [cCdfType] = getType(anyValue)
%GETTYPE given a matlab object, find it's corresponding CDF type.

% CDF_TT2000  is not avalable to matlab, this will be a problem

	persistent dMatlab2Cdf
	
	if isempty(dMatlab2Cdf)
		dMatlab2Cdf = containers.Map(...
			{...
				'char','string','int8','uint8','int16',...
				'uint16','int32','uint32','single','double',...
				'datetime','logical'...
			}, ...
			{...
				'CDF_CHAR','CDF_CHAR','CDF_INT1','CDF_UINT1','CDF_INT2',...
				'CDF_UINT2','CDF_INT4','CDF_UINT4','CDF_REAL4','CDF_REAL8',...
				'CDF_EPOCH','CDF_UINT1'...
				}...
		);
	end
	
	% Get the corresponding CDF type given a matlab variable
	if iscell(anyValue); anyValue = anyValue{1}; end
		
	cClass = class(anyValue);
	if ~ isKey(dMatlab2Cdf, cClass)
		throw(MException(...
			'cdf:unconvertableType', ...
			'Matlab type %s is not representable in CDF files', cClass...
		));
	end
	
	cCdfType = dMatlab2Cdf(cClass);	
end

